import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>
      <div className='px-8'>
      <Link href='inputTitle'>
        <a className="pa-display">Create Platform</a>
      </Link>
      </div>
    </div>
  )
}

export default Home
