import type { NextPage } from 'next'
import Head from 'next/head'
import { Input } from 'components/Input'
import { useFormStateProvider } from 'context'
import { useRouter } from 'next/router'
import { Header } from '../components/Header'
import { HeroText } from 'components/HeroText'
import { HeroWrapper } from 'components/HeroWrapper'

const InputSymbol: NextPage = () => {
  const router = useRouter()

  const { symbol, setSymbol } = useFormStateProvider()

  const handleKeyPress = (e: any) => {
    if (e.key === 'Enter') {
      router.push('/inputCurationPass')
    }
  }

  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>
      <Header route={'./inputTitle'} />
      <HeroWrapper>
        <HeroText
          text={
            <>
              next,&nbsp;<span className="hidden sm:block"></span>choose a&nbsp;
              <span className="pa-displayLight">symbol</span>
            </>
          }
        />
        <Input
          value={symbol}
          placeholder="e.g. NEO"
          onChange={(e: any) => setSymbol(e.currentTarget.value)}
          onKeyPress={handleKeyPress}
          route={'./inputCurationPass'}
        />
      </HeroWrapper>
    </div>
  )
}

export default InputSymbol
