import type { NextPage } from 'next'
import Head from 'next/head'
import { Input } from 'components/Input'
import { useMachine } from '@xstate/react'
import { deployPlatform } from 'utils/deployPlatform'
import { useRouter } from 'next/router'

const InputTitle: NextPage = () => {
  const router = useRouter()
  const [current, state, send] = useMachine(deployPlatform, {
    actions: {
      goToNextPage: () => {
        router.push('/inputCurationPass')
      },
    },
  })
  console.log(current.context.title)
//   console.log(state.context.title)

  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>
      <div className="px-8">
        <Input
          label={'Input Title'}
          placeholder="e.g. Neosound"
          onChange={(e: any) => send({ type: 'INPUT_TITLE', title: e.target.value })}
        />
        <br></br>
        <button onClick={() => send('CONFIRM_TITLE')}>Confirm Title</button>
      </div>
    </div>
  )
}

export default InputTitle
