import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Input } from 'components/Input'
import { useRouter } from 'next/router'
import { useFormStateProvider } from 'context'

const InputCurationPass: NextPage = () => {
  const router = useRouter()

  const { curationPass, setCurationPass } = useFormStateProvider()

  const handleKeyPress = (e: any) => {
    if (e.key === 'Enter') {
      router.push('/inputMedia')
    }
  }

  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>
      <div className="px-8">
        <Input
          label={'Input Curation Pass'}
          placeholder="e.g. 0x34fe32e6442d14d923953a537b8163365630b5a7"
          onChange={(e: any) => setCurationPass(e.currentTarget.value)}
          onKeyPress={handleKeyPress}
        />
        {/* <Link href="/inputCurationPass">
          <a>Next</a>
        </Link> */}
        <br></br>
        <Link href="/inputSymbol">
          <a>Go Back</a>
        </Link>
      </div>
    </div>
  )
}

export default InputCurationPass
